MvcApiPersonajesAws/Models/ErrorViewModel.cs
namespace MvcApiPersonajesAws.Models
{
    public class ErrorViewModel
    {
        public string? RequestId { get; set; }

        public bool ShowRequestId => !string.IsNullOrEmpty(RequestId);
    }
}

MvcApiPersonajesAws/Models/Personaje.cs
namespace MvcApiPersonajesAws.Models
{
    public class Personaje
    {
        public int IdPersonaje { get; set; }
        public string Nombre { get; set; }
        public string Imagen { get; set; }
    }
}

MvcApiPersonajesAws/Controllers/HomeController.cs
using Microsoft.AspNetCore.Mvc;
using MvcApiPersonajesAws.Models;
using System.Diagnostics;

namespace MvcApiPersonajesAws.Controllers
{
    public class HomeController : Controller
    {
        private readonly ILogger<HomeController> _logger;

        public HomeController(ILogger<HomeController> logger)
        {
            _logger = logger;
        }

        public IActionResult Index()
        {
            return View();
        }

        public IActionResult Privacy()
        {
            return View();
        }

        [ResponseCache(Duration = 0, Location = ResponseCacheLocation.None, NoStore = true)]
        public IActionResult Error()
        {
            return View(new ErrorViewModel { RequestId = Activity.Current?.Id ?? HttpContext.TraceIdentifier });
        }
    }
}

MvcApiPersonajesAws/Controllers/PersonajesController.cs
using Microsoft.AspNetCore.Mvc;
using MvcApiPersonajesAws.Models;
using MvcApiPersonajesAws.Services;

namespace MvcApiPersonajesAws.Controllers
{
    public class PersonajesController : Controller
    {
        private ServiceApiPersonajes service; 

        public PersonajesController(ServiceApiPersonajes service)
        {
            this.service = service;
        }

        public async Task <IActionResult> Index()
        {
            List<Personaje>personajes = await this.service.GetPersonajesAsync();
            return View(personajes);
        }
        public IActionResult CreatePersonajes()
        {
            return View();
        }

        [HttpPost]
        public async Task<IActionResult> CreatePersonajes(Personaje personaje)
        {
            await this.service.CreatePersonajesAsync(personaje.Nombre, personaje.Imagen);
            return RedirectToAction("Index");
        }
       
        public async Task<IActionResult>Edit()
        {
            return View();
        }
        [HttpPost]
        public async Task<IActionResult>Edit(Personaje per)
        {
            await this.service.UpdatePersonajesAsync(per.IdPersonaje, per.Nombre, per.Imagen);
            return RedirectToAction("Index");
        }
    }
}

MvcApiPersonajesAws/Views/Home/Index.cshtml
@{
    ViewData["Title"] = "Home Page";
}
@section Scripts{
    <script>
        $(document).ready(function(){
            $("#botonload").click(function(){
                var url = "https://18.208.220.165/api/personajes"
                $.get(url, function (data) {
                    var html = "";
                    $.each(data, function (index, personaje) {
                        html += "<li class='list-group-item'>";
                        html += personaje.nombre;
                        html += "<img src ='" + personaje.imagen + "'" + "style='width:80px;height:80px'/>";
                        html += "</li>";
                    })
                    $("#capapersonajes").html(html);
                })
            })
        })
    </script>
}
<div class="text-center">
    <h1 class="display-4">Personajes</h1>
    <button id="botonload" class="btn btn-info">
        Load Api Personajes AWS
    </button>
   <ul class="list-group" id="capapersonajes"></ul>
</div>

MvcApiPersonajesAws/Views/Personajes/CreatePersonajes.cshtml
@model MvcApiPersonajesAws.Models.Personaje

@{
    ViewData["Title"] = "CreatePersonajes";
}

<h1>CreatePersonajes</h1>

<h4>Personaje</h4>
<hr />
<div class="row">
    <div class="col-md-4">
        <form asp-action="CreatePersonajes">
            <div asp-validation-summary="ModelOnly" class="text-danger"></div>
            <div class="form-group">
                <label asp-for="IdPersonaje" class="control-label"></label>
                <input asp-for="IdPersonaje" class="form-control" />
                <span asp-validation-for="IdPersonaje" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Nombre" class="control-label"></label>
                <input asp-for="Nombre" class="form-control" />
                <span asp-validation-for="Nombre" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Imagen" class="control-label"></label>
                <input asp-for="Imagen" class="form-control" />
                <span asp-validation-for="Imagen" class="text-danger"></span>
            </div>
            <div class="form-group">
                <input type="submit" value="Create" class="btn btn-primary" />
            </div>
        </form>
    </div>
</div>

<div>
    <a asp-action="Index">Back to List</a>
</div>

@section Scripts {
    @{await Html.RenderPartialAsync("_ValidationScriptsPartial");}
}

MvcApiPersonajesAws/Views/Personajes/Edit.cshtml
@model MvcApiPersonajesAws.Models.Personaje

@{
    ViewData["Title"] = "Edit";
}

<h1>Edit</h1>

<h4>Personaje</h4>
<hr />
<div class="row">
    <div class="col-md-4">
        <form asp-action="Edit">
            <div asp-validation-summary="ModelOnly" class="text-danger"></div>
            <div class="form-group">
                <label asp-for="IdPersonaje" class="control-label"></label>
                <input asp-for="IdPersonaje" class="form-control" />
                <span asp-validation-for="IdPersonaje" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Nombre" class="control-label"></label>
                <input asp-for="Nombre" class="form-control" />
                <span asp-validation-for="Nombre" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Imagen" class="control-label"></label>
                <input asp-for="Imagen" class="form-control" />
                <span asp-validation-for="Imagen" class="text-danger"></span>
            </div>
            <div class="form-group">
                <input type="submit" value="Save" class="btn btn-primary" />
            </div>
        </form>
    </div>
</div>

<div>
    <a asp-action="Index">Back to List</a>
</div>

@section Scripts {
    @{await Html.RenderPartialAsync("_ValidationScriptsPartial");}
}

MvcApiPersonajesAws/Views/Personajes/Index.cshtml
@model IEnumerable<MvcApiPersonajesAws.Models.Personaje>

@{
    ViewData["Title"] = "Index";
}

<h1>Index</h1>

<p>
    <a asp-action="CreatePersonajes" asp-controller="Personajes">Create New</a>
</p>
<table class="table">
    <thead>
        <tr>
            <th>
                @Html.DisplayNameFor(model => model.IdPersonaje)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.Nombre)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.Imagen)
            </th>
            <th></th>
        </tr>
    </thead>
    <tbody>
@foreach (var item in Model) {
        <tr>
            <td>
                @Html.DisplayFor(modelItem => item.IdPersonaje)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.Nombre)
            </td>
            <td>
               <img src="@item.Imagen" class="w-25 y-25"/>
            </td>
            <td>
               <a asp-action="Edit" asp-controller="Personajes" >Edit</a>
            </td>
        </tr>
}
    </tbody>
</table>

MvcApiPersonajesAws/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - MvcApiPersonajesAws</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/site.css" asp-append-version="true" />
    <link rel="stylesheet" href="~/MvcApiPersonajesAws.styles.css" asp-append-version="true" />
</head>
<body>
    <header>
        <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light bg-white border-bottom box-shadow mb-3">
            <div class="container-fluid">
                <a class="navbar-brand" asp-area="" asp-controller="Home" asp-action="Index">MvcApiPersonajesAws</a>
                <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                        aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="navbar-collapse collapse d-sm-inline-flex justify-content-between">
                    <ul class="navbar-nav flex-grow-1">
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Index">Home</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Personajes" asp-action="Index">Personajes</a>
                        </li>
                    </ul>
                </div>
            </div>
        </nav>
    </header>
    <div class="container">
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>

    <footer class="border-top footer text-muted">
        <div class="container">
            &copy; 2024 - MvcApiPersonajesAws - <a asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
        </div>
    </footer>
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    @await RenderSectionAsync("Scripts", required: false)
</body>
</html>